name: CI

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: taiki-e/install-action@nextest
      - run: cargo fmt --all --check
      - run: cargo check --workspace
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo nextest run -E 'all() - package(calendar)'
      - run: cargo test --doc